version: '3'


services:
  db:
    container_name: user_db
    image: mysql
    restart: on-failure
    environment:
      MYSQL_DATABASE: 'users-db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    expose:
      - '3306'
    networks:
      - users-db-network
    volumes:
      - micro-users-volume:/var/lib/mysql

  micro-users:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: micro-users
    ports:
      - '8001:8001'
    networks:
      - users-db-network
      - api-network
      - rabbit-network
    depends_on:
      - db

  rabbitmq:
    restart: always
    container_name: rabbitmq
    image: rabbitmq
    expose:
      - "5672"
    networks:
      - rabbit-network

volumes:
  micro-users-volume:
    external: true

networks:
  users-db-network:
    external: true

  api-network:
    external: true

  rabbit-network:
    external: true